### ISSUE TITLE
rewrite in rust.

### ISSUE THREAD

**Issue by KieranCrossland** [pac-ac/osakaOS#1]
[:)](https://tenor.com/en-GB/view/troll-troll-face-gif-25116980)

**Comment by keef1212** [comment]
rust sucks

**Comment by KieranCrossland** [comment]
> rust sucks
"osakaOS is a 32 bit, singletasking, megalithic operating system that is made with a focus on unconventional/ridicoulous design choices."

It'd suit OsakaOS well then.

**Comment by Ronterox** [comment]
Rewrite on Brainfuck

**Comment by sorae42** [comment]
imagine putting an overhead on something already fast enough

**Comment by apprehensions** [comment]
Rust is just a glorified C++ designed by a corporation to make their giant glowieware better with a miniscule amount, it won't make a real difference.

Rewrite in C.

**Comment by AbdalrahmanEm** [comment]
Rewriting it in x86 assembly is obviously the superior option

**Comment by figere99** [comment]
Rewrite moat of it in Lisp and license it as AGPL

**Comment by JohnHillsCodeProjects** [comment]
> Rewrite moat of it in Lisp and license it under the AGPL

Ah, an excellent, refined choice sir.

**Comment by KieranCrossland** [comment]
> Rust is just a glorified C++ designed by a corporation to make their giant glowieware better with a miniscule amount, it won't make a real difference.
> 
> Rewrite in C.

Based.
I hate rust, I was just trolling.
C99 for life.

**Comment by KieranCrossland** [comment]
I am closing this issue since I have been enlightened on the shitness of rust.
Install gentoo.

**Comment by KieranCrossland** [comment]
I am closing this issue since I have been enlightened on the shitness of rust.
Install gentoo.

**Comment by chuckling2** [comment]
rewrite in binary
