### ISSUE TITLE
oh yeah

### ISSUE THREAD

**Issue by ariabk** [pac-ac/osakaOS#13]
-----BEGIN PGP MESSAGE-----

hQGMA6ZAJeFIHYGwAQv/c40XgF8A2/TUXftQa+XUkkHgFEUITejXIDpG06HxjYfT
pmKiHvx5Sgy4ryN39iGIw8vATynRCq3on1gf2MM6tIpQfDtbjIyI1nkZoqOYOr5x
hA27pULdyiUZhqYScDpnEUGYtwvOqwGdgYYCZo5oLttSj++Fj4oCa0IXoPSjSJrW
OvvZaqh1hVhGSxF21ZV2N7qMqlLbE6AlK4XdasiHGDenzeHrUs5cRJC6J50MtSOv
NgKZIQgy3zgA6LKqpABV8M/zhscIk7wopzEAMlFVS5VKMIBTwNVYwPmhPRzL5Tw3
JR2Bf8IKlTcR8xIpLX0HjpO3XW8Mq6EtiD1D7S+j0mX1+4U7RvzwnqcRr0LlDaJw
dYJcMtI+5/0+x0lreP4F8Y38LzAP0QGlNvt/XXynRyHsUoApHN1IcTQRzALxEN7/
NzkVcvIQN7niB0n9iQ0Ow5Fe2BrOQvGhzawk3fF1RKQNvBMylOFhu+6TkLO23mQ0
HkKrr4nCRkoFdTjEQBF00lcBQKOxjVlgZjlgP6Q2S8KfFMBNJJ3pQR+Vu7gfgyYj
F2JmdV0RjSz9jHfEzWj0elr/sn9qqUugMJkg00u5Ya894it/+1j5o6dzelXWAytu
/+nBZiGAaP8=
=lnKo
-----END PGP MESSAGE-----

**Comment by pac-ac** [comment]
teeheehee
