### ISSUE TITLE
Booting sequence stuck in "Initializing, stage 3" -- Audio Problems 

### ISSUE THREAD

**Issue by selselse** [pac-ac/osakaOS#9]
I am not that well equipped with Linux knowledge, but I have managed to initialize the booting process with:

`sudo qemu-system-x86_64 -enable-kvm -boot menu=on   -drive id=disk,file=Image.img,format=raw,if=none   -device piix4-ide,id=piix4 -device ide-hd,drive=disk,bus=piix4.0   -cpu 486 -smp 1 -m 1G   -vga virtio   -audiodev pa,id=pa0,server=unix:/tmp/pulse-socket` 

The QEMU window shows up, but regardless of which device I choose to boot it from the sequence either gets stuck in second or the third stage. I have g++, binutils, libc6-dev-i386, qemu-system-x86, grub2, xorriso installed. Couldn't downgrade qemu-system so that it would register ` -machine pcspk-audiodev=po0 `as the proper version wasn't in the list of available versions. 
![Screenshot from 2024-02-27 21-55-46](https://github.com/pac-ac/osakaOS/assets/81919734/1882a21d-13b3-406a-9ed8-523cbb670e29)

**Comment by pac-ac** [comment]
Did you add load-module module-native-protocol-unix auth-anonymous=1
socket=/tmp/pulse-socket to /etc/pulse/default.pa ? Also are you using the
precompiled iso image or compiling from source? You can try starting
without audio, or compiling from source to see if it changes anything, but
these are the default makefile configs which worked on both my debain and
mint builds so the most I can suggest is to see if there's some way you can
finesse qemu to get it past the hardware init. The makefile also uses the
dd utility to copy the iso image to the virtual disk and boot from there,
maybe booting from live image works for you? (although it didn't work with
my version of qemu so idk)

If all else fails you can try using virtualbox or other vm software,
virtualbox offers the same hardware support in this case (except for the pc
speaker I believe) and is also easier to configure.

**Comment by selselse** [comment]
Sorry for the late response! I was trying to compile it from source, whereby qemu didn't let me. After a research, the problem was due to qemu not supporting -`machine pcspk-audiodev` and couldn't get it working. Now I used the precompiled iso image in order to run the OS on Boxes and tested the audio there. The `Beep`command doesn't seem to give away any sound. Maybe this has something to do with pulseaudio? I added the line` load-module module-native-protocol-unix auth-anonymous=1 socket=/tmp/pulse-socket` to `/etc/pulse/default.pa `(bottom).

**Comment by pac-ac** [comment]
As far as I'm aware your pulseaudio should be able to emulate the audio
device, depending on how you boot the OS (and with what parameters) it
might not even be able to emulate a PCspeaker, not told to, or doesn't know
where to look.
Did you try the "-soundhw" option in place of "-audiodev
pa,id=pa0,server=unix:/tmp/pulse-socket \ -machine pcspk-audiodev=pa0" with
qemu? A lot of people have trouble with emulation in qemu because of its
complex cli and not the best documentation.
If you find some other VM software with PC speaker emulation and can't get
qemu to work then I would advise to use that instead, or whatever makes it
easier for you.

**Comment by selselse** [comment]
It works no problem in a VM, I am following your work on your youtube channel. Love it!
